---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: minecraft-server
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/component: server

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

...
