---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: minecraft-server
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/component: server

spec:
  endpoints:
    - port: metrics
      scheme: http
      interval: 60s

  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft
      app.kubernetes.io/component: server

  jobLabel: app.kubernetes.io/name

...
