---
apiVersion: v1
kind: Service

metadata:
  name: minecraft-server
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/component: server

spec:
  selector:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/component: server

  ports:
    - name: server
      port: 25565
    - name: rcon
      port: 25575
    - name: metrics
      port: 9150

...
